-- Paper trading desk: specs (the plan, armed pre-market) and trades (fills
-- against those specs). Created ad-hoc in production on 2026-08-06/07; this
-- file makes the schema reproducible — until it existed, a fresh rebuild had
-- no DDL for either table anywhere in the repos.
--
-- RLS is enabled with NO policies: the public REST API (anon key) is deny-all,
-- matching every other table. The scheduler, paper trader, and MCP server all
-- connect via direct Postgres and are unaffected. These tables sat with RLS
-- disabled — anon held full privileges including TRUNCATE — until 2026-08-07.

CREATE TABLE IF NOT EXISTS paper_specs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date DATE NOT NULL,
    book TEXT NOT NULL,               -- 'gamma_iday' | 'swing'
    ticker TEXT NOT NULL,
    direction TEXT NOT NULL,
    setup TEXT NOT NULL,
    entry_trigger NUMERIC NOT NULL,
    stop NUMERIC NOT NULL,
    target NUMERIC NOT NULL,
    r_dollars NUMERIC NOT NULL DEFAULT 100,
    status TEXT NOT NULL DEFAULT 'armed',  -- armed | skipped_binary | filled | expired
    rationale TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'board',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_paper_specs_date ON paper_specs (trade_date, book);

CREATE TABLE IF NOT EXISTS paper_trades (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    spec_id BIGINT NOT NULL REFERENCES paper_specs(id),
    entered_at TIMESTAMPTZ NOT NULL,
    entry_px NUMERIC NOT NULL,
    exited_at TIMESTAMPTZ,
    exit_px NUMERIC,
    exit_reason TEXT,
    r_multiple NUMERIC,
    slippage_haircut NUMERIC NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_paper_trades_spec ON paper_trades (spec_id);

ALTER TABLE paper_specs ENABLE ROW LEVEL SECURITY;
ALTER TABLE paper_trades ENABLE ROW LEVEL SECURITY;
